### ISSUE TITLE
using die()

### ISSUE THREAD

**Issue by exyjerome** [jake-cryptic/patchy#1]
if (accountLoggedIn()) {
	 die("Error: You are logged in.");
} else {

Why are you using die() to show a simple message? 

Just echo a message or header -> location home..

die() should only really be used to stop script execution..

**Comment by jake-cryptic** [comment]
It's just a habit, I will improve this in the next version

**Comment by jake-cryptic** [comment]
If said file is login.php or create.php it is because those scripts are called using ajax and so the response is on a webpage
